---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
